apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    name: teamcity
spec:
  containers:
  - image: jetbrains/teamcity-server
    name: teamcity
    ports:
    - containerPort: 8111
      protocol: TCP