apiVersion: v1
kind: Secret
metadata:
  name: teamcity-secrets
type: Opaque
data:
  rootPassword: cGFzc3dvcmQ=
  userPassword: cGFzc3dvcmQ=
  database.properties: |
    I1R1ZSBPY3QgMDEgMTM6NDA6MTMgR01UIDIwMTkKY29ubmVjdGlvblByb3BlcnRpZXMudXNlcj10ZWFtY2l0eQpjb25uZWN0aW9uUHJvcGVydGllcy5wYXNzd29yZD1wYXNzd29yZApjb25uZWN0aW9uVXJsPWpkYmNcOm15c3FsXDovL215c3FsXDozMzA2L3RlYW1jaXR5Cg==
