apiVersion: v1
kind: Pod
metadata:
  name: teamcity
  labels:
    name: teamcity
spec:
  containers:
  - image: jetbrains/teamcity-server
    name: teamcity
    ports:
    - containerPort: 8111
      protocol: TCP
    volumeMounts:
    - name: teamcity-persistent-storage
      mountPath: /data/teamcity_server/datadir
    - name: database-properties
      mountPath: /data/teamcity_server/datadir/config/database.properties
      subPath: database.properties
  volumes:
  - name: teamcity-persistent-storage
    persistentVolumeClaim:
      claimName: teamcity-pv-claim
  - name: database-properties
    secret:
      secretName: teamcity-secrets
      items:
      - key: database.properties
        path: database.properties
