apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-config
  labels:
    app: teamcity
data:
  MYSQL_DATABASE: "teamcity"
  MYSQL_USER: "teamcity"
  mysql_binlog_format.cnf: |
    [mysqld]
    binlog-format=mixed
  database_properties: |
    #Tue Oct 01 13:40:13 GMT 2019
    connectionProperties.user=teamcity
    connectionProperties.password=password
    connectionUrl=jdbc\:mysql\://mysql\:3306/teamcity
