apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-config
  labels:
    app: teamcity
data:
  MYSQL_DATABASE: "teamcity"
  MYSQL_USER: "teamcity"
  mysql_binlog_format.cnf: |
    [mysqld]
    binlog-format=mixed